apiVersion: v1
kind: Service
metadata:
  name: mm-lb
spec:
  selector:
    app: main-menu
  ports:
    - protocol: TCP
      port: 80        # Exposed externally
      targetPort: 80  # Maps to container port
  type: LoadBalancer
