apiVersion: v1
kind: Service
metadata:
  name: main-menu-np-svc
  labels:
    app: main-menu
spec:
  type: NodePort
  selector:
    app: main-menu
  ports:
    - protocol: TCP
      port: 80         # Service Port
      targetPort: 80   # Pod Port
      nodePort: 30080  # Exposes the service on Node's port 30080
  type: NodePort
