apiVersion: v1
kind: Service
metadata:
  name: nc-lb
spec:
  selector:
    app: n-calci
  ports:
    - protocol: TCP
      port: 80        # Exposed externally
      targetPort: 80  # Maps to container port
  type: LoadBalancer
