apiVersion: v1
kind: Service
metadata:
  name: s-calci-np-svc
  labels:
    app: s-calci
spec:
  type: NodePort
  selector:
    app: s-calci
  ports:
    - protocol: TCP
      port: 80         # Service Port
      targetPort: 80   # Pod Port
      nodePort: 30082  # Exposes the service on Node's port 30080
  type: NodePort
