apiVersion: v1
kind: Pod
metadata:
  name: s-calci
  labels:
    app: s-calci
spec:
  containers:
  - name: nginx
    image: nginx:latest
    # Mount the custom HTML over the default Nginx content
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    configMap:
      name: s-calci-html
